remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
- jekyll-remote-theme
- jekyll-include-cache
title: "Shadow Walker"
description: ""
minimal_mistakes_skin: "dark"
url: "www.shadowshields.xyz"
locale: # zh

# Site Author
author:
  name             : "Shadow Walker"
  avatar           : "/assets/images/avatar.jpg"
  bio              : "shadow walker"

paginate: 5 # amount of posts to show
paginate_path: /page:num/
# paginate_path: /recent/page:num/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/
  recipes:
    output: true
    permalink: /:collection/:path/
  pets:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/     

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

